name: Postman-collection

on:
  push:
    branches: [ master ]

  workflow_dispatch:

  schedule:
    - cron: "0 6 * * *"

jobs:
  run-postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: List project files
        run: ls -la

      - name: Run Postman Collection
        run: |
          mkdir -p newman
          newman run Zflow.postman_collection.json \
          -r htmlextra \
          --reporter-htmlextra-export newman/index.html || true

      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: newman-report
          path: newman/

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/
